handler: math
dataset_path: "/p/project1/envcomp/yll/.cache/huggingface/datasets/math500_offline"  # local offline dataset
dataset_subset: default # which subset on huggingface
question_key: problem
answer_key: answer
dataset_split: test
templating_parameters: 
  template: "Return your final response within \\boxed{{}}. {problem}"
# optional. Not supported yet. 
# fewshot_config:
#   - question: ...
#   - target:  ...
# num_fewshot: 0
