handler: numina
dataset_path: "AI-MO/NuminaMath-CoT"
dataset_subset: null
dataset_split: train
question_key: problem
answer_key: solution
templating_parameters:
  template: "Return your final response within \\boxed{{}}. {prompt}"
preprocess_config:
  filter_difficulty: true
  math_difficulty_lower_bound: 4
  math_difficulty_upper_bound: 9
  source: math
